// PNW Draft — an 82-0 / 162-0 style roster-builder game for PNW college
// baseball. Each round you spin a random level + team and draft one player into
// a position-locked lineup (9 hitters) + staff (5 pitchers). When the roster is
// full, a level-aware model grades it into a stylized 56-game record.
//
// Data + the scoring constants come from GET /api/v1/pnw-draft (generated by
// scripts/build_pnw_draft_json.py). The sim here is intentionally light: every
// player already carries a level-adjusted talent score (off / pit) computed in
// the generator, and meta.win_map holds the calibration so records stay stable.
//
// Original game built by an intern; this is the productionized port (level-aware
// scoring, two-way de-dupe, deadlock-proof spins, share card).

import { useEffect, useMemo, useRef, useState } from 'react'
import InternCredit from '../components/InternCredit'

const HPOS = ['C', '1B', '2B', 'SS', '3B', 'RF', 'CF', 'LF', 'DH']
const PLBLS = ['SP1', 'SP2', 'SP3', 'SP4', 'RP']
const LEVEL_ORDER = ['JUCO', 'NAIA', 'D3', 'D2', 'D1']

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)]
const mean = (arr, k) => arr.reduce((s, x) => s + x[k], 0) / (arr.length || 1)
const sum = (arr, k) => arr.reduce((s, x) => s + x[k], 0)

function emptyRoster() {
  return [
    ...HPOS.map((p) => ({ label: p, type: 'hitter', pos: p, player: null })),
    ...PLBLS.map((l) => ({ label: l, type: 'pitcher', pos: null, player: null })),
  ]
}

export default function PnwDraft() {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    let alive = true
    fetch('/api/v1/pnw-draft')
      .then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json() })
      .then((d) => { if (alive) setData(d) })
      .catch((e) => { if (alive) setError(String(e)) })
    return () => { alive = false }
  }, [])

  if (error) {
    return <div className="max-w-3xl mx-auto py-16 text-center text-gray-500 dark:text-gray-400">Couldn't load the PNW Draft ({error}).</div>
  }
  if (!data) {
    return <div className="max-w-3xl mx-auto py-16 text-center text-gray-500 dark:text-gray-400">Loading the draft pool…</div>
  }
  return <Game data={data} />
}

function Game({ data }) {
  const { hitters, pitchers, teams, logos = {}, meta } = data

  // Index pools by team for fast lookup.
  const hByTeam = useMemo(() => {
    const m = {}
    for (const h of hitters) (m[h.t] ||= []).push(h)
    return m
  }, [hitters])
  const pByTeam = useMemo(() => {
    const m = {}
    for (const p of pitchers) (m[p.t] ||= []).push(p)
    return m
  }, [pitchers])
  const levels = useMemo(
    () => LEVEL_ORDER.filter((l) => (teams[l] || []).length), [teams])

  const [roster, setRoster] = useState(emptyRoster)
  const [phase, setPhase] = useState('spin') // spin | pick | result
  const [spin, setSpin] = useState(null)      // {lvl, team}
  const [skips, setSkips] = useState({ team: 1, level: 1 })
  const [sortH, setSortH] = useState('off')
  const [sortP, setSortP] = useState('off')
  const [posF, setPosF] = useState('all')
  const [reel, setReel] = useState(null)      // {lvl, team} during spin animation
  const [spinning, setSpinning] = useState(false)
  const [note, setNote] = useState(null)
  const reelTimer = useRef(null)

  useEffect(() => () => clearInterval(reelTimer.current), [])

  const usedPids = useMemo(
    () => new Set(roster.filter((s) => s.player).map((s) => s.player.pid)),
    [roster])
  const slotFilled = (pos) => {
    const sl = roster.find((s) => s.type === 'hitter' && s.pos === pos)
    return sl ? !!sl.player : true
  }
  const pitcherSlotsLeft = roster.filter((s) => s.type === 'pitcher' && !s.player).length
  const hitterCount = roster.filter((s) => s.type === 'hitter' && s.player).length
  const pitcherCount = roster.filter((s) => s.type === 'pitcher' && s.player).length
  const filled = hitterCount + pitcherCount

  // How many legal picks a team offers given the current roster — used to make
  // every settled spin guaranteed-playable (no dead ends).
  const legalCount = (team) => {
    const dhOpen = !slotFilled('DH')
    let n = 0
    for (const h of hByTeam[team] || []) {
      if (usedPids.has(h.pid)) continue
      if (!slotFilled(h.p) || dhOpen) n++
    }
    if (pitcherSlotsLeft > 0) {
      for (const p of pByTeam[team] || []) if (!usedPids.has(p.pid)) n++
    }
    return n
  }

  // Pick a (level, team) that has at least one legal pick. newTeamOnly keeps the
  // level and forces a different team (used by the team skip).
  const chooseTarget = (newTeamOnly) => {
    let last = null
    for (let i = 0; i < 300; i++) {
      let lvl, team
      if (newTeamOnly && spin) {
        lvl = spin.lvl
        const opts = (teams[lvl] || []).filter((t) => t !== spin.team)
        team = pick(opts.length ? opts : teams[lvl])
      } else {
        lvl = pick(levels)
        team = pick(teams[lvl])
      }
      last = { lvl, team }
      if (legalCount(team) > 0) return last
    }
    return last
  }

  const animateTo = (target, msg) => {
    if (spinning) return
    setSpinning(true)
    setNote(msg || null)
    let ticks = 0
    clearInterval(reelTimer.current)
    reelTimer.current = setInterval(() => {
      const rl = pick(levels)
      setReel({ lvl: rl, team: pick(teams[rl]) })
      if (++ticks >= 12) {
        clearInterval(reelTimer.current)
        setReel(null)
        setSpin(target)
        setPhase('pick')
        setPosF('all')
        setSpinning(false)
      }
    }, 55)
  }

  const doSpin = () => animateTo(chooseTarget(false))

  const skipTeam = () => {
    if (!skips.team || !spin || spinning) return
    setSkips((s) => ({ ...s, team: s.team - 1 }))
    animateTo(chooseTarget(true))
  }
  const skipLevel = () => {
    if (!skips.level || !spin || spinning) return
    setSkips((s) => ({ ...s, level: s.level - 1 }))
    // Force a different level.
    let t = null
    for (let i = 0; i < 300; i++) {
      const lvl = pick(levels.filter((l) => l !== spin.lvl))
      const team = pick(teams[lvl])
      t = { lvl, team }
      if (legalCount(team) > 0) break
    }
    animateTo(t)
  }

  const advance = (next) => {
    if (next.every((s) => s.player)) {
      setPhase('result')
    } else {
      setPhase('spin')
      setSpin(null)
    }
  }

  const draftHitter = (h) => {
    if (usedPids.has(h.pid)) return
    const next = roster.map((s) => ({ ...s }))
    // Prefer the player's natural position; fall back to DH (any hitter can DH).
    let target = next.find((s) => s.type === 'hitter' && s.pos === h.p && !s.player)
    if (!target) target = next.find((s) => s.type === 'hitter' && s.pos === 'DH' && !s.player)
    if (!target) return
    target.player = h
    setRoster(next)
    advance(next)
  }
  const draftPitcher = (p) => {
    if (usedPids.has(p.pid)) return
    const next = roster.map((s) => ({ ...s }))
    const target = next.find((s) => s.type === 'pitcher' && !s.player)
    if (!target) return
    target.player = p
    setRoster(next)
    advance(next)
  }

  const reset = () => {
    setRoster(emptyRoster())
    setPhase('spin'); setSpin(null); setSkips({ team: 1, level: 1 })
    setSortH('off'); setSortP('off'); setPosF('all'); setNote(null)
  }

  // ── Sorted, filtered pick lists for the current team ──
  const curHitters = useMemo(() => {
    if (!spin) return []
    let list = (hByTeam[spin.team] || []).filter((h) => h.l === spin.lvl)
    if (posF !== 'all') list = list.filter((h) => h.p === posF)
    const cmp = {
      off: (a, b) => b.off - a.off, avg: (a, b) => b.avg - a.avg,
      obp: (a, b) => b.obp - a.obp, slg: (a, b) => b.slg - a.slg,
      hr: (a, b) => b.hr - a.hr, rbi: (a, b) => b.rbi - a.rbi,
      wrc: (a, b) => b.wrc - a.wrc, war: (a, b) => b.war - a.war,
    }
    return [...list].sort(cmp[sortH] || cmp.off)
  }, [spin, hByTeam, posF, sortH])

  const curPitchers = useMemo(() => {
    if (!spin) return []
    const list = (pByTeam[spin.team] || []).filter((p) => p.l === spin.lvl)
    const cmp = {
      off: (a, b) => b.pit - a.pit, era: (a, b) => a.era - b.era,
      fip: (a, b) => a.fip - b.fip, k9: (a, b) => b.k9 - a.k9,
      whip: (a, b) => a.whip - b.whip, war: (a, b) => b.war - a.war,
    }
    return [...list].sort(cmp[sortP] || cmp.off)
  }, [spin, pByTeam, sortP])

  const result = useMemo(() => {
    if (phase !== 'result') return null
    return computeResult(roster, meta)
  }, [phase, roster, meta])

  // ── Render ──
  return (
    <div className="max-w-4xl mx-auto px-3 sm:px-4 py-6">
      <style>{SCOPED_CSS}</style>

      <div className="mb-4">
        <h1 className="text-3xl sm:text-4xl font-black text-nw-teal dark:text-gray-100">PNW Draft</h1>
        <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
          Spin a team, draft a player, build the best roster in the Pacific Northwest. 14 picks (9 hitters, position-locked, plus 5 pitchers), one shot at a perfect 56-0.
        </p>
        <InternCredit names="Oliver Duthie" className="mt-2" />
      </div>

      <div id="pnwdraft">
        <RosterGrid roster={roster} logos={logos} filled={filled} phase={phase} />
        <Chips filled={filled} hitterCount={hitterCount} pitcherCount={pitcherCount} skips={skips} />

        {phase !== 'result' ? (
          <>
            <SpinCard
              spin={spin} reel={reel} spinning={spinning} note={note}
              round={Math.min(filled + 1, 14)} skips={skips}
              onSpin={doSpin} onSkipTeam={skipTeam} onSkipLevel={skipLevel}
            />
            {phase === 'pick' && spin && (
              <Picker
                spin={spin} logos={logos}
                hitters={curHitters} pitchers={curPitchers}
                hNeed={9 - hitterCount} pNeed={5 - pitcherCount}
                sortH={sortH} sortP={sortP} setSortH={setSortH} setSortP={setSortP}
                posF={posF} setPosF={setPosF}
                usedPids={usedPids} slotFilled={slotFilled} dhOpen={!slotFilled('DH')}
                pitcherSlotsLeft={pitcherSlotsLeft}
                onDraftH={draftHitter} onDraftP={draftPitcher}
              />
            )}
          </>
        ) : (
          <Result result={result} roster={roster} logos={logos} meta={meta} onReset={reset} />
        )}
      </div>
    </div>
  )
}

// ── Scoring (level-aware, uses the talent scores baked into the JSON) ──
function computeResult(roster, meta) {
  const h = roster.filter((s) => s.type === 'hitter' && s.player).map((s) => s.player)
  const p = roster.filter((s) => s.type === 'pitcher' && s.player).map((s) => s.player)
  const hs = mean(h, 'off')                       // mean offense talent
  const ipTot = sum(p, 'ip') || 1
  const ps = p.reduce((s, x) => s + x.pit * x.ip, 0) / ipTot  // IP-weighted pitching talent
  const w = meta.weights || { h: 0.55, p: 0.45 }
  const total = w.h * hs + w.p * ps

  // Piecewise win mapping from meta.win_map (worst→3, average→30, best→56).
  const wm = meta.win_map
  let wins
  if (total <= wm.mean) {
    const frac = (total - wm.worst_total) / Math.max(wm.mean - wm.worst_total, 1e-6)
    wins = wm.worst_wins + frac * (wm.center_wins - wm.worst_wins)
  } else {
    const frac = (total - wm.mean) / Math.max(wm.best_total - wm.mean, 1e-6)
    wins = wm.center_wins + frac * (wm.best_wins - wm.center_wins)
  }
  wins = Math.max(0, Math.min(56, Math.round(wins)))

  const norm = (v, b) => Math.max(0, Math.min(100, Math.round(((v - b.min) / Math.max(b.max - b.min, 1e-6)) * 100)))
  return {
    wins, losses: 56 - wins,
    offBar: norm(hs, meta.off_bar), pitBar: norm(ps, meta.pit_bar),
    havg: mean(h, 'avg'), hobp: mean(h, 'obp'), hslg: mean(h, 'slg'),
    hr: sum(h, 'hr'), rbi: sum(h, 'rbi'), hwrc: mean(h, 'wrc'),
    pera: mean(p, 'era'), pwhip: mean(p, 'whip'), pk9: mean(p, 'k9'), pfip: mean(p, 'fip'),
  }
}

// ── Subcomponents ──
function TeamLogo({ logos, team, size = 14 }) {
  const url = logos[team]
  if (!url) return null
  return <img src={url} alt="" width={size} height={size}
    style={{ width: size, height: size, objectFit: 'contain', flexShrink: 0 }}
    loading="lazy" onError={(e) => { e.target.style.display = 'none' }} />
}

function RosterGrid({ roster, logos, filled, phase }) {
  return (
    <div className="roster-grid">
      {roster.map((slot, i) => {
        const p = slot.player
        const active = i === filled && phase !== 'result'
        return (
          <div key={i} className={'rslot ' + (p ? (slot.type === 'hitter' ? 'fh' : 'fp') : 'emp') + (active ? ' active' : '')}>
            <div className="rl">{slot.label}</div>
            <div className="rn">{p ? p.n : '--'}</div>
            <div className="rs">
              {p ? (
                <span style={{ display: 'inline-flex', alignItems: 'center', gap: 3 }}>
                  <TeamLogo logos={logos} team={p.t} size={10} />
                  {slot.type === 'hitter' ? p.avg.toFixed(3) : p.era.toFixed(2) + 'E'}
                </span>
              ) : ''}
            </div>
          </div>
        )
      })}
    </div>
  )
}

function Chips({ filled, hitterCount, pitcherCount, skips }) {
  return (
    <div className="chips">
      <div className="chip cd"><strong>{filled}</strong>/14 drafted</div>
      <div className="chip cg"><strong>{hitterCount}</strong>/9 hitters</div>
      <div className="chip cb"><strong>{pitcherCount}</strong>/5 pitchers</div>
      {!!skips.team && <div className="chip cd">🎲 <strong>{skips.team}</strong> team skip</div>}
      {!!skips.level && <div className="chip cd">⚡ <strong>{skips.level}</strong> level skip</div>}
    </div>
  )
}

function SpinCard({ spin, reel, spinning, note, round, skips, onSpin, onSkipTeam, onSkipLevel }) {
  const disp = reel || spin
  const lvl = disp ? disp.lvl : '--'
  const team = disp ? disp.team : '--'
  return (
    <div className="spin-card">
      <div className="spin-lbl">Round {round} of 14</div>
      <div className="spin-boxes">
        <div className="sbox">
          <div className="sbl">Level</div>
          <div className={disp ? 'sbv lvl ' + lvl : 'sbv'}>{lvl}</div>
        </div>
        <div className="sbox">
          <div className="sbl">Team</div>
          <div className="sbv">{team}</div>
        </div>
      </div>
      <div className="btn-row">
        {!spin && (
          <button className="btn bspin" onClick={onSpin} disabled={spinning}>🎰 SPIN</button>
        )}
        {spin && !!skips.team && (
          <button className="btn bsec" onClick={onSkipTeam} disabled={spinning}>Skip Team ({skips.team})</button>
        )}
        {spin && !!skips.level && (
          <button className="btn bsec" onClick={onSkipLevel} disabled={spinning}>Skip Level ({skips.level})</button>
        )}
      </div>
      {note && <div className="hint">{note}</div>}
      {spin && !note && <div className="hint">Hitters fill their position (anyone can DH) · pitchers fill in order</div>}
    </div>
  )
}

function Sorter({ label, val, opts, onChange }) {
  return (
    <span style={{ fontSize: 11, fontFamily: 'monospace', color: '#4a6080' }}>
      {label}:{' '}
      <select className="ssel" value={val} onChange={(e) => onChange(e.target.value)}>
        {opts.map(([v, t]) => <option key={v} value={v}>{t}</option>)}
      </select>
    </span>
  )
}

function Picker({ spin, logos, hitters, pitchers, hNeed, pNeed, sortH, sortP, setSortH, setSortP,
  posF, setPosF, usedPids, slotFilled, dhOpen, pitcherSlotsLeft, onDraftH, onDraftP }) {
  return (
    <div className="picker-card">
      <div className="phdr">
        <h3 style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <TeamLogo logos={logos} team={spin.team} size={18} />
          {spin.team} <span className={'lvl ' + spin.lvl}>{spin.lvl}</span>
        </h3>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
          <Sorter label="H" val={sortH} onChange={setSortH} opts={[['off', 'TALENT'], ['war', 'WAR'], ['avg', 'AVG'], ['obp', 'OBP'], ['slg', 'SLG'], ['hr', 'HR'], ['wrc', 'wRC+']]} />
          <Sorter label="P" val={sortP} onChange={setSortP} opts={[['off', 'TALENT'], ['war', 'WAR'], ['era', 'ERA'], ['fip', 'FIP'], ['k9', 'K/9'], ['whip', 'WHIP']]} />
        </div>
      </div>

      <div className="pcols">
        {/* Hitters */}
        <div className="pcol">
          <div className="chdr"><span className="doth" /> HITTERS ({hNeed} needed)</div>
          <div className="posf">
            {['all', ...HPOS].map((pos) => (
              <button key={pos} className={'pfb' + (posF === pos ? ' on' : '')} onClick={() => setPosF(pos)}>
                {pos === 'all' ? 'All' : pos}
              </button>
            ))}
          </div>
          <div className="cscroll">
            {!hitters.length ? (
              <div className="ecol">No hitters here at {spin.team}</div>
            ) : hitters.map((p) => {
              const taken = usedPids.has(p.pid)
              const posFull = slotFilled(p.p)
              const placeable = !posFull || dhOpen
              const dis = taken || !placeable
              const willDH = !taken && posFull && dhOpen
              return (
                <div key={p.pid} className={'prow' + (dis ? ' dis' : '')} onClick={() => !dis && onDraftH(p)}>
                  <div className="ptop">
                    <div className="pnm">{p.n}</div>
                    <div className="pri">
                      <span className={'pbg' + (posFull && !taken ? ' full' : '')}>
                        {willDH ? 'DH' : p.p}{posFull && !taken && !willDH ? ' X' : ''}
                      </span>
                      <span className={'pwr' + (p.war >= 0 ? '' : ' neg')}>{(p.war >= 0 ? '+' : '') + p.war.toFixed(1)}</span>
                    </div>
                  </div>
                  <div className="psb">{p.t} ({p.l}) · {p.g}G</div>
                  <div className="pst">
                    <span className="ps hl"><strong>{p.avg.toFixed(3)}</strong></span>
                    <span className="ps"><strong>{p.obp.toFixed(3)}</strong> OBP</span>
                    <span className="ps"><strong>{p.slg.toFixed(3)}</strong> SLG</span>
                    <span className="ps"><strong>{p.hr}</strong> HR</span>
                    <span className="ps"><strong>{p.wrc.toFixed(0)}</strong> wRC+</span>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Pitchers */}
        <div className="pcol">
          <div className="chdr"><span className="dotp" /> PITCHERS ({pNeed} needed)</div>
          <div className="cscroll">
            {!pitchers.length ? (
              <div className="ecol">No pitchers here at {spin.team}</div>
            ) : pitchers.map((p) => {
              const taken = usedPids.has(p.pid)
              const dis = taken || pitcherSlotsLeft === 0
              return (
                <div key={p.pid} className={'prow' + (dis ? ' dis' : '')} onClick={() => !dis && onDraftP(p)}>
                  <div className="ptop">
                    <div className="pnm">{p.n}</div>
                    <div className="pri">
                      <span className="pbg">{p.sv > 0 ? 'RP' : 'SP'}</span>
                      <span className={'pwr' + (p.war >= 0 ? '' : ' neg')}>{(p.war >= 0 ? '+' : '') + p.war.toFixed(1)}</span>
                    </div>
                  </div>
                  <div className="psb">{p.t} ({p.l}) · {p.g}G · {p.w}W{p.sv ? ' ' + p.sv + 'SV' : ''}</div>
                  <div className="pst">
                    <span className="ps hl"><strong>{p.era.toFixed(2)}</strong> ERA</span>
                    <span className="ps"><strong>{p.whip.toFixed(2)}</strong> WHIP</span>
                    <span className="ps"><strong>{p.k9.toFixed(1)}</strong> K/9</span>
                    <span className="ps"><strong>{p.fip.toFixed(2)}</strong> FIP</span>
                    <span className="ps"><strong>{p.ip}</strong> IP</span>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </div>
    </div>
  )
}

function Result({ result: r, roster, logos, meta, onReset }) {
  const [copied, setCopied] = useState(false)
  const win = r.wins >= 44
  const verdict =
    r.wins === 56 ? 'UNDEFEATED — PNW immortals' :
    r.wins >= 50 ? 'Conference champions' :
    r.wins >= 44 ? 'Postseason bound' :
    r.wins >= 34 ? 'Missed the mark' : 'Time to rebuild'

  const shareText = useMemo(() => {
    const lineup = roster.filter((s) => s.player)
      .map((s) => `${s.label}: ${s.player.n} (${s.player.t})`).join('\n')
    return `PNW Draft — I went ${r.wins}-${r.losses}! ${r.wins === 56 ? '🏆' : r.wins >= 44 ? '🔥' : ''}\n\n${lineup}\n\nBuild yours at nwbaseballstats.com/draft`
  }, [roster, r])

  const copy = async () => {
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(shareText)
      } else {
        const ta = document.createElement('textarea')
        ta.value = shareText
        ta.style.position = 'fixed'; ta.style.opacity = '0'
        document.body.appendChild(ta); ta.select()
        document.execCommand('copy')
        document.body.removeChild(ta)
      }
    } catch { /* clipboard blocked — still show feedback so the user can select manually */ }
    setCopied(true); setTimeout(() => setCopied(false), 2000)
  }

  return (
    <>
      <div className="res-card">
        <div className={'rbanner ' + (win ? 'win' : 'loss')}>
          <div className="rrec">{r.wins}-{r.losses}</div>
          <div className="rlbl">56-game regular season</div>
          <div className="rverd">{verdict}</div>
        </div>
        <div className="sgrid">
          <div className="scell">
            <div className="slbl">Offense</div>
            <div className="sval">{r.offBar}<span style={{ fontSize: 13, color: '#4a6080' }}>/100</span></div>
            <div className="sbar"><div className="sfill sfh" style={{ width: r.offBar + '%' }} /></div>
          </div>
          <div className="scell">
            <div className="slbl">Pitching</div>
            <div className="sval">{r.pitBar}<span style={{ fontSize: 13, color: '#4a6080' }}>/100</span></div>
            <div className="sbar"><div className="sfill sfp" style={{ width: r.pitBar + '%' }} /></div>
          </div>
          <div className="scell">
            <div className="slbl">Slash Line</div>
            <div className="sval" style={{ fontSize: 15 }}>{r.havg.toFixed(3)} / {r.hobp.toFixed(3)} / {r.hslg.toFixed(3)}</div>
            <div className="ssub">{r.hr} HR · {r.rbi} RBI · {r.hwrc.toFixed(0)} wRC+</div>
          </div>
          <div className="scell">
            <div className="slbl">Rotation</div>
            <div className="sval" style={{ fontSize: 15 }}>{r.pera.toFixed(2)} ERA / {r.pwhip.toFixed(2)} WHIP</div>
            <div className="ssub">{r.pk9.toFixed(1)} K/9 · {r.pfip.toFixed(2)} FIP</div>
          </div>
        </div>
      </div>

      <div className="fros">
        <div className="frh">FINAL ROSTER</div>
        <div className="fgrid">
          {roster.map((slot, i) => {
            const p = slot.player
            return (
              <div key={i} className="fs">
                <div className="fsl">{slot.label}</div>
                <div className="fsn" style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                  <TeamLogo logos={logos} team={p?.t} size={13} />{p ? p.n : '--'}
                </div>
                <div className="fss">
                  {p ? (slot.type === 'hitter'
                    ? `${p.t} (${p.l}) · ${p.avg.toFixed(3)}/${p.obp.toFixed(3)}/${p.slg.toFixed(3)} · ${p.hr}HR`
                    : `${p.t} (${p.l}) · ${p.era.toFixed(2)} ERA · ${p.whip.toFixed(2)} WHIP`) : ''}
                </div>
              </div>
            )
          })}
        </div>
      </div>

      <div className="btn-row" style={{ marginTop: '.25rem' }}>
        <button className="btn bspin" onClick={copy}>{copied ? '✓ COPIED' : '📋 COPY RESULT'}</button>
        <button className="btn bsec" onClick={onReset}>DRAFT AGAIN</button>
      </div>
      <p className="hint" style={{ marginTop: '.6rem' }}>
        Records are level-adjusted: a 150 wRC+ at JUCO counts less than a 150 at D1. Pool: {meta.n_hitters} hitters + {meta.n_pitchers} pitchers, {meta.season} season.
      </p>
    </>
  )
}

// Intern's original CSS, scoped under #pnwdraft so it can't leak into the site.
const SCOPED_CSS = `
#pnwdraft{font-family:Georgia,serif;color:#e8dcc8;background:#0a1628;border:1px solid #1e3a5f;border-radius:14px;padding:1rem}
#pnwdraft .roster-grid{display:grid;grid-template-columns:repeat(7,1fr);border:1px solid #1e3a5f;border-radius:10px;overflow:hidden;background:#080f1c;margin-bottom:1rem}
#pnwdraft .rslot{padding:.5rem .45rem;border-right:1px solid #1e3a5f;border-bottom:1px solid #1e3a5f;min-width:0}
#pnwdraft .rslot:nth-child(7n){border-right:none}
#pnwdraft .rslot:nth-last-child(-n+7){border-bottom:none}
#pnwdraft .rslot.active{box-shadow:inset 0 0 0 2px #e8c96a}
#pnwdraft .rl{font-size:9px;font-family:monospace;letter-spacing:.08em;color:#4a6080;text-transform:uppercase;margin-bottom:2px}
#pnwdraft .rn{font-size:11px;font-weight:700;color:#e8dcc8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
#pnwdraft .rs{font-size:9px;color:#4a6080;font-family:monospace;margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
#pnwdraft .rslot.emp .rn{color:#2a4060;font-style:italic;font-weight:400}
#pnwdraft .rslot.fh{background:#0a1e10}
#pnwdraft .rslot.fp{background:#0a1028}
#pnwdraft .chips{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:1rem}
#pnwdraft .chip{padding:4px 12px;border-radius:20px;font-size:12px;font-family:monospace;border:1px solid}
#pnwdraft .cd{background:#0f2438;border-color:#1e3a5f;color:#8a9ab0}
#pnwdraft .cg{background:#0a2518;border-color:#1e5c35;color:#5ecf8a}
#pnwdraft .cb{background:#0a1028;border-color:#1e3a8f;color:#6ab0f0}
#pnwdraft .chip strong{font-weight:700}
#pnwdraft .spin-card{background:#0f1e38;border:1px solid #1e3a5f;border-radius:10px;padding:1.25rem;margin-bottom:1rem}
#pnwdraft .spin-lbl{font-size:11px;font-family:monospace;color:#4a6080;letter-spacing:.08em;text-transform:uppercase;margin-bottom:.75rem}
#pnwdraft .spin-boxes{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:1rem}
#pnwdraft .sbox{background:#080f1c;border:1px solid #1e3a5f;border-radius:8px;padding:.75rem 1rem;text-align:center;min-height:74px;display:flex;flex-direction:column;align-items:center;justify-content:center}
#pnwdraft .sbl{font-size:10px;font-family:monospace;color:#4a6080;text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px}
#pnwdraft .sbv{font-size:18px;font-weight:700;color:#e8dcc8}
#pnwdraft .lvl{display:inline-block;padding:3px 12px;border-radius:12px;font-size:13px;font-weight:700;font-family:monospace}
#pnwdraft .JUCO{background:#0a2518;color:#5ecf8a;border:1px solid #1e5c35}
#pnwdraft .NAIA{background:#1a1400;color:#e8c96a;border:1px solid #5c4a00}
#pnwdraft .D3{background:#0a1a38;color:#6ab0f0;border:1px solid #1e3a8f}
#pnwdraft .D2{background:#1a0a0a;color:#f08080;border:1px solid #8f1e1e}
#pnwdraft .D1{background:#e8c96a;color:#0a0800;border:1px solid #c0a040}
#pnwdraft .btn-row{display:flex;gap:8px}
#pnwdraft .btn{padding:9px 18px;border-radius:7px;font-size:13px;font-weight:700;cursor:pointer;border:1px solid;font-family:monospace;letter-spacing:.04em;transition:all .15s}
#pnwdraft .btn:active{transform:scale(.97)}
#pnwdraft .bspin{background:#e8c96a;color:#0a0800;border-color:#c0a040;flex:2}
#pnwdraft .bspin:hover{background:#f0d878}
#pnwdraft .bspin:disabled{opacity:.4;cursor:not-allowed}
#pnwdraft .bsec{background:#0f2438;color:#8a9ab0;border-color:#1e3a5f;flex:1;font-size:11px}
#pnwdraft .bsec:hover{background:#162d48;color:#e8dcc8}
#pnwdraft .hint{font-size:11px;color:#4a6080;font-family:monospace;text-align:center;margin-top:.6rem}
#pnwdraft .picker-card{background:#0f1e38;border:1px solid #1e3a5f;border-radius:10px;overflow:hidden;margin-bottom:1rem}
#pnwdraft .phdr{padding:.875rem 1rem;border-bottom:1px solid #1e3a5f;display:flex;align-items:center;justify-content:space-between;background:#080f1c;flex-wrap:wrap;gap:8px}
#pnwdraft .phdr h3{font-size:14px;color:#e8dcc8}
#pnwdraft .ssel{font-size:11px;padding:4px 7px;border:1px solid #1e3a5f;border-radius:6px;background:#080f1c;color:#8a9ab0;cursor:pointer;font-family:monospace}
#pnwdraft .pcols{display:flex;border-top:1px solid #1e3a5f;min-height:200px}
#pnwdraft .pcol{flex:1;min-width:0;display:flex;flex-direction:column}
#pnwdraft .pcol:first-child{border-right:1px solid #1e3a5f}
#pnwdraft .chdr{padding:6px 10px;background:#080f1c;font-size:10px;font-family:monospace;letter-spacing:.1em;text-transform:uppercase;color:#4a6080;border-bottom:1px solid #0f1e38;display:flex;align-items:center;gap:6px;flex-shrink:0}
#pnwdraft .doth{display:inline-block;width:6px;height:6px;border-radius:50%;background:#3a9c5a}
#pnwdraft .dotp{display:inline-block;width:6px;height:6px;border-radius:50%;background:#2a5aaf}
#pnwdraft .cscroll{overflow-y:auto;max-height:360px;flex:1}
#pnwdraft .cscroll::-webkit-scrollbar{width:3px}
#pnwdraft .cscroll::-webkit-scrollbar-track{background:#0a1628}
#pnwdraft .cscroll::-webkit-scrollbar-thumb{background:#1e3a5f;border-radius:2px}
#pnwdraft .posf{display:flex;gap:4px;flex-wrap:wrap;padding:6px 8px;border-bottom:1px solid #0f1e38;background:#0a1628}
#pnwdraft .pfb{padding:2px 7px;border-radius:10px;font-size:10px;font-weight:700;cursor:pointer;border:1px solid #1e3a5f;background:transparent;color:#4a6080;font-family:monospace}
#pnwdraft .pfb.on{background:#1e5c35;color:#5ecf8a;border-color:#3a9c5a}
#pnwdraft .prow{padding:.6rem .75rem;border-bottom:1px solid #0f1e38;cursor:pointer;transition:background .1s}
#pnwdraft .prow:last-child{border-bottom:none}
#pnwdraft .prow:hover{background:#162d48}
#pnwdraft .prow.dis{opacity:.35;cursor:not-allowed;pointer-events:none}
#pnwdraft .ptop{display:flex;align-items:flex-start;justify-content:space-between;gap:6px}
#pnwdraft .pnm{font-size:12px;font-weight:700;color:#e8dcc8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1}
#pnwdraft .pri{display:flex;flex-direction:column;align-items:flex-end;gap:2px;flex-shrink:0}
#pnwdraft .pbg{padding:1px 6px;border-radius:5px;font-size:10px;font-weight:700;font-family:monospace;background:#1e3a5f;color:#8a9ab0}
#pnwdraft .pbg.full{background:#3a1010;color:#f08080}
#pnwdraft .pwr{font-size:10px;font-family:monospace;font-weight:700;color:#5ecf8a}
#pnwdraft .pwr.neg{color:#f08080}
#pnwdraft .psb{font-size:10px;color:#4a6080;font-family:monospace;margin-top:2px}
#pnwdraft .pst{display:flex;gap:5px;margin-top:3px;flex-wrap:wrap}
#pnwdraft .ps{font-size:10px;color:#6a8aaa;font-family:monospace}
#pnwdraft .ps strong{color:#c8c0b0}
#pnwdraft .hl strong{color:#e8c96a}
#pnwdraft .ecol{padding:2rem .75rem;text-align:center;color:#4a6080;font-size:11px;font-family:monospace}
#pnwdraft .res-card{border:1px solid #1e3a5f;border-radius:10px;overflow:hidden;margin-bottom:1rem}
#pnwdraft .rbanner{padding:2.5rem 1.5rem;text-align:center}
#pnwdraft .rbanner.win{background:linear-gradient(160deg,#0a2518,#1e5c35)}
#pnwdraft .rbanner.loss{background:linear-gradient(160deg,#1a0808,#3a1010)}
#pnwdraft .rrec{font-size:56px;font-weight:700;letter-spacing:-.03em;line-height:1;color:#e8c96a;font-family:monospace;text-shadow:0 0 30px rgba(232,201,106,.4)}
#pnwdraft .rlbl{font-size:13px;margin-top:8px;color:#8a9ab0;font-family:monospace}
#pnwdraft .rverd{font-size:17px;font-weight:700;margin-top:14px;color:#e8dcc8}
#pnwdraft .sgrid{display:grid;grid-template-columns:1fr 1fr;background:#080f1c}
#pnwdraft .scell{padding:1rem;border-right:1px solid #0f1e38;border-bottom:1px solid #0f1e38}
#pnwdraft .scell:nth-child(2n){border-right:none}
#pnwdraft .slbl{font-size:10px;font-family:monospace;letter-spacing:.08em;color:#4a6080;text-transform:uppercase;margin-bottom:4px}
#pnwdraft .sval{font-size:20px;font-weight:700;color:#e8dcc8;font-family:monospace}
#pnwdraft .sbar{height:5px;background:#0f1e38;border-radius:3px;overflow:hidden;margin-top:7px}
#pnwdraft .sfill{height:100%;border-radius:3px}
#pnwdraft .sfh{background:linear-gradient(90deg,#1e5c35,#5ecf8a)}
#pnwdraft .sfp{background:linear-gradient(90deg,#0f2744,#4a9af0)}
#pnwdraft .ssub{font-size:11px;font-family:monospace;color:#6a8aaa;margin-top:5px}
#pnwdraft .fros{background:#0f1e38;border:1px solid #1e3a5f;border-radius:10px;overflow:hidden;margin-bottom:1rem}
#pnwdraft .frh{padding:.75rem 1rem;border-bottom:1px solid #1e3a5f;background:#080f1c;font-size:12px;font-weight:700;font-family:monospace;color:#e8c96a;letter-spacing:.06em}
#pnwdraft .fgrid{display:grid;grid-template-columns:1fr 1fr}
#pnwdraft .fs{padding:.65rem .9rem;border-right:1px solid #0f1e38;border-bottom:1px solid #0f1e38}
#pnwdraft .fs:nth-child(2n){border-right:none}
#pnwdraft .fsl{font-size:10px;font-family:monospace;color:#4a6080;text-transform:uppercase;letter-spacing:.08em;margin-bottom:2px}
#pnwdraft .fsn{font-size:13px;font-weight:700;color:#e8dcc8}
#pnwdraft .fss{font-size:11px;color:#4a6080;font-family:monospace;margin-top:1px}
@media(max-width:560px){
  #pnwdraft .roster-grid{grid-template-columns:repeat(5,1fr)}
  #pnwdraft .rslot:nth-child(7n){border-right:1px solid #1e3a5f}
  #pnwdraft .rslot:nth-child(5n){border-right:none}
  #pnwdraft .rslot:nth-last-child(-n+7){border-bottom:1px solid #1e3a5f}
  #pnwdraft .rrec{font-size:46px}
}
`
